# Generated by Django 5.0.6 on 2024-06-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='time',
        ),
    ]
