version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: /order_food/dockerfiles/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    ports:
      - "54321:5432"
    env_file:
      - order_food/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
