# Generated by Django 5.0.6 on 2024-06-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
